import React, { useState } from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import Navbar from "../components/Navbar";

// Styled components
const ProjectContainer = styled.div`
  margin-bottom: 20px;
  border: 1px solid #ccc;
  padding: 20px;
`;

const PledgeDiv = styled.div`
  align-itmes: center;
  padding: 20px;
`;

const ProjectName = styled.h3`
  color: #333;
`;

const ProjectDescription = styled.p`
  color: #666;
`;

const ProjectDetails = styled.p`
  color: #666;
  margin-top: 10px;
`;

const DonationInput = styled.input`
  margin-top: 10px;
  padding: 5px;
`;

const DonateButton = styled.button`
  margin-top: 10px;
  padding: 8px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  cursor: pointer;
  &:hover {
    background-color: #0056b3;
  }
`;

const CreatePledge = () => {
  const [projects, setProjects] = useState([]);
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    goal: '',
    deadline: ''
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    setProjects([...projects, formData]);
    setFormData({
      name: '',
      description: '',
      goal: '',
      deadline: ''
    });
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });
  };

  return (
    <>
      <Head>
        <title>OpenSource: A Decentralized Crowdfunding Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <PledgeDiv>
        <h1>Create New Pledge</h1>
        <form onSubmit={handleSubmit}>
          <div>
            <label htmlFor="name">Project Name:</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label htmlFor="description">Project Description:</label>
            <input
              type="text"
              id="description"
              name="description"
              value={formData.description}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label htmlFor="goal">Fund Goal:</label>
            <input
              type="number"
              id="goal"
              name="goal"
              value={formData.goal}
              onChange={handleChange}
              required
            />
          </div>
          <div>
            <label htmlFor="deadline">Deadline:</label>
            <input
              type="date"
              id="deadline"
              name="deadline"
              value={formData.deadline}
              onChange={handleChange}
              required
            />
          </div>
          <button type="submit">Submit</button>
        </form>
      </PledgeDiv>
      <div>
        <h1>Crowdfunding Projects</h1>
        {projects.map((project, index) => (
          <ProjectContainer key={index}>
            <ProjectName>{project.name}</ProjectName>
            <ProjectDescription>{project.description}</ProjectDescription>
            <ProjectDetails>Goal: ${project.goal} | Deadline: {project.deadline}</ProjectDetails>
            <DonationInput type="text" placeholder="Enter amount to donate" />
            <DonateButton>Donate</DonateButton>
          </ProjectContainer>
        ))}
      </div>
    </>
  );
};

export default CreatePledge;


