import Head from "next/head";
import Navbar from "../components/Navbar";
import styled from 'styled-components';
import LoginPage from "../components/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>OpenSource: A Decentralized Crowdfunding Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {/* <LoginPage /> */}
      
    </>
  );
}
