import React, { useState } from 'react';
import Navbar from "../components/Navbar";
import CreatePledge from "../components/PledgeCreation";
import Head from 'next/head';

const PledgePage = () => {
    const [projects, setProjects] = useState([]);

    const addProject = (formData) => {
        setProjects([...projects, formData]);
    };

    return (
        <>
          <Head>
            <title>OpenSource: A Decentralized Crowdfunding Platform</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <CreatePledge/>
        </>
      );
    }
    

    export default PledgePage;

