import React, { useState } from 'react';
import Navbar from "../components/Navbar";
import Head from 'next/head';
import styled from 'styled-components';
import CryptoTracker from '../components/CryptoTracker';


const Divider = styled.div`
  justify-content: space-evenly;
  display: flex;
  width: 100%;
  flex-direction: row;
`;

    export default function Home() {
    return (
        <>
          <Head>
            <title>Whale Track: Tracking the biggest Cryptocurrency wallets</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Navbar />

        {/* <Divider /> */}


        {/* <CryptoTracker /> */}
        </>
      );
    }

